User data
czarny247/CourseDashboard pull request #1
Opened 2019-08-04 17:10 UTC by ChopSeeGuy

2019-08-05 20:03 UTC, czarny247 requested changes
Few things to be done.

2019-08-05 20:03 UTC, czarny247 commented on src/UserData.hpp
> +    std::string name_;
Explicitly tell that this section is private. We know that it is but it will increase readability.
Also follow this pattern: _"By placing the public section first, everything that is of interest to a user is gathered in the beginning of the class definition. The protected section may be of interest to designers when considering inheriting from the class. The private section contains details that should have the least general interest."_ - from https://www.doc.ic.ac.uk/lab/cplus/c++.rules/chap6.html

2019-08-05 20:03 UTC, czarny247 commented on src/main.cpp
> +    sleep(1);
What is it for?

2019-08-05 20:03 UTC, czarny247 commented on src/main.cpp
> +#include "Group.hpp"
Keep empty line between includes and main.

2019-08-05 20:03 UTC, czarny247 commented on src/main.cpp
> +    std::cout << "List of students: " << std::endl;
You can make operator<< for UserData class (but you also need toString() method for enum class Group).
operator<<: https://medium.com/@nonuruzun/overloading-input-output-operators-in-c-a2a74c5dda8a
enum class toString - the easiest way is to use switch.

2019-08-05 23:43 UTC, ChopSeeGuy commented on src/main.cpp
> +    sleep(1);
My fantasy, thanks for notice. Deleted.

2019-08-11 19:34 UTC, czarny247 approved these changes

2019-08-11 19:34 UTC, czarny247 commented on src/UserData.cpp
> +             std::system("clear");
Move these couts to separate function - e.g. printMenu() (name is up to you)

2019-08-11 19:34 UTC, czarny247 commented on src/UserData.cpp
> +             std::system("clear");
move it to anonymous namespace ( namespace { //here }).

2019-08-11 19:34 UTC, czarny247 commented on src/UserData.cpp
> +                             std::cout << "Change group to: " << std::endl;
Move this part with group to separate function - consider using >> for Group.

2019-08-11 19:35 UTC, czarny247 approved these changes

2019-08-11 19:35 UTC, merged